#include "StdAfx.h"

#include "Tr2RenderContextEnum.h"
#include "ALLog.h"

bool g_requestDebugMarkers = false;
bool g_brokenMacOSNvidiaDrivers = false;

using namespace Tr2RenderContextEnum;

Tr2RenderContextEnum::PixelFormat Tr2RenderContextEnum::ConvertD3DBackBufferFormat( /*D3DFORMAT*/ unsigned fmt )
{
	switch( fmt )
	{
		case 116 /*D3DFMT_A32B32G32R32F*/: return PIXEL_FORMAT_R32G32B32A32_FLOAT;
        case 113 /*D3DFMT_A16B16G16R16F*/: return PIXEL_FORMAT_R16G16B16A16_FLOAT;
		case  36 /*D3DFMT_A16B16G16R16 */: return PIXEL_FORMAT_R16G16B16A16_UNORM;
		case  35 /*D3DFMT_A2R10G10B10  */: return PIXEL_FORMAT_R10G10B10A2_UNORM;
		case  32 /*D3DFMT_A8B8G8R8     */: return PIXEL_FORMAT_R8G8B8A8_UNORM;
		case  23 /*D3DFMT_R5G6B5       */: return PIXEL_FORMAT_B5G6R5_UNORM;
		case  25 /*D3DFMT_A1R5G5B5     */: return PIXEL_FORMAT_B5G5R5A1_UNORM;
		case  21 /*D3DFMT_A8R8G8B8     */: return PIXEL_FORMAT_B8G8R8A8_UNORM;
		case  22 /*D3DFMT_X8R8G8B8     */: return PIXEL_FORMAT_B8G8R8X8_UNORM;
	}
	return PIXEL_FORMAT_UNKNOWN;
}

Tr2RenderContextEnum::PixelFormat Tr2RenderContextEnum::MakeTypeless( Tr2RenderContextEnum::PixelFormat format )
{
	using namespace Tr2RenderContextEnum;
	switch( format )
	{
	case PIXEL_FORMAT_R32G32B32A32_FLOAT:
	case PIXEL_FORMAT_R32G32B32A32_UINT:
	case PIXEL_FORMAT_R32G32B32A32_SINT:
		return PIXEL_FORMAT_R32G32B32A32_TYPELESS;
	case PIXEL_FORMAT_R32G32B32_FLOAT:
	case PIXEL_FORMAT_R32G32B32_UINT:
	case PIXEL_FORMAT_R32G32B32_SINT:
		return PIXEL_FORMAT_R32G32B32_TYPELESS;
	case PIXEL_FORMAT_R16G16B16A16_FLOAT:
	case PIXEL_FORMAT_R16G16B16A16_UINT:
	case PIXEL_FORMAT_R16G16B16A16_SINT:
	case PIXEL_FORMAT_R16G16B16A16_UNORM:
	case PIXEL_FORMAT_R16G16B16A16_SNORM:
		return PIXEL_FORMAT_R16G16B16A16_TYPELESS;
	case PIXEL_FORMAT_R32G32_FLOAT:
	case PIXEL_FORMAT_R32G32_UINT:
	case PIXEL_FORMAT_R32G32_SINT:
		return PIXEL_FORMAT_R32G32_TYPELESS;
	case PIXEL_FORMAT_R10G10B10A2_UINT:
	case PIXEL_FORMAT_R10G10B10A2_UNORM:
		return PIXEL_FORMAT_R10G10B10A2_TYPELESS;
	case PIXEL_FORMAT_R8G8B8A8_UNORM_SRGB:
	case PIXEL_FORMAT_R8G8B8A8_UNORM:
	case PIXEL_FORMAT_R8G8B8A8_UINT:
	case PIXEL_FORMAT_R8G8B8A8_SINT:
	case PIXEL_FORMAT_R8G8B8A8_SNORM:
		return PIXEL_FORMAT_R8G8B8A8_TYPELESS;
	case PIXEL_FORMAT_R16G16_FLOAT:
	case PIXEL_FORMAT_R16G16_UNORM:
	case PIXEL_FORMAT_R16G16_UINT:
	case PIXEL_FORMAT_R16G16_SNORM:
	case PIXEL_FORMAT_R16G16_SINT:
		return PIXEL_FORMAT_R16G16_TYPELESS;
	case PIXEL_FORMAT_R32_FLOAT:
	case PIXEL_FORMAT_R32_UINT:
	case PIXEL_FORMAT_R32_SINT:
		return PIXEL_FORMAT_R32_TYPELESS;
	case PIXEL_FORMAT_R8G8_UNORM:
	case PIXEL_FORMAT_R8G8_UINT:
	case PIXEL_FORMAT_R8G8_SNORM:
	case PIXEL_FORMAT_R8G8_SINT:
		return PIXEL_FORMAT_R8G8_TYPELESS;
	case PIXEL_FORMAT_R16_FLOAT:
	case PIXEL_FORMAT_R16_UNORM:
	case PIXEL_FORMAT_R16_UINT:
	case PIXEL_FORMAT_R16_SNORM:
	case PIXEL_FORMAT_R16_SINT:
		return PIXEL_FORMAT_R16_TYPELESS;
	case PIXEL_FORMAT_R8_UNORM:
	case PIXEL_FORMAT_R8_UINT:
	case PIXEL_FORMAT_R8_SNORM:
	case PIXEL_FORMAT_R8_SINT:
		return PIXEL_FORMAT_R8_TYPELESS;
	case PIXEL_FORMAT_BC1_UNORM_SRGB:
	case PIXEL_FORMAT_BC1_UNORM:
		return PIXEL_FORMAT_BC1_TYPELESS;
	case PIXEL_FORMAT_BC2_UNORM_SRGB:
	case PIXEL_FORMAT_BC2_UNORM:
		return PIXEL_FORMAT_BC2_TYPELESS;
	case PIXEL_FORMAT_BC3_UNORM_SRGB:
	case PIXEL_FORMAT_BC3_UNORM:
		return PIXEL_FORMAT_BC3_TYPELESS;
	case PIXEL_FORMAT_BC4_SNORM:
	case PIXEL_FORMAT_BC4_UNORM:
		return PIXEL_FORMAT_BC4_TYPELESS;
	case PIXEL_FORMAT_BC5_SNORM:
	case PIXEL_FORMAT_BC5_UNORM:
		return PIXEL_FORMAT_BC5_TYPELESS;
	case PIXEL_FORMAT_B8G8R8A8_UNORM:
	case PIXEL_FORMAT_B8G8R8A8_UNORM_SRGB:
		return PIXEL_FORMAT_B8G8R8A8_TYPELESS;
	case PIXEL_FORMAT_B8G8R8X8_UNORM:
	case PIXEL_FORMAT_B8G8R8X8_UNORM_SRGB:
		return PIXEL_FORMAT_B8G8R8X8_TYPELESS;
	case PIXEL_FORMAT_BC6H_UF16:
	case PIXEL_FORMAT_BC6H_SF16:
		return PIXEL_FORMAT_BC6H_TYPELESS;
	case PIXEL_FORMAT_BC7_UNORM_SRGB:
	case PIXEL_FORMAT_BC7_UNORM:
		return PIXEL_FORMAT_BC7_TYPELESS;
	case PIXEL_FORMAT_D24_UNORM_S8_UINT:
		return PIXEL_FORMAT_R24G8_TYPELESS;
	case PIXEL_FORMAT_D32_FLOAT:
		return PIXEL_FORMAT_R32_TYPELESS;
	default:
		return format;
	}
}

Tr2RenderContextEnum::PixelFormat Tr2RenderContextEnum::MakeSrgb( Tr2RenderContextEnum::PixelFormat format )
{
	switch( format )
	{
	case PIXEL_FORMAT_R8G8B8A8_TYPELESS:
	case PIXEL_FORMAT_R8G8B8A8_UNORM:
		return PIXEL_FORMAT_R8G8B8A8_UNORM_SRGB;

	case PIXEL_FORMAT_BC1_TYPELESS:
	case PIXEL_FORMAT_BC1_UNORM:
		return PIXEL_FORMAT_BC1_UNORM_SRGB;

	case PIXEL_FORMAT_BC2_TYPELESS:
	case PIXEL_FORMAT_BC2_UNORM:
		return PIXEL_FORMAT_BC2_UNORM_SRGB;

	case PIXEL_FORMAT_BC3_TYPELESS:
	case PIXEL_FORMAT_BC3_UNORM:
		return PIXEL_FORMAT_BC3_UNORM_SRGB;

	case PIXEL_FORMAT_B8G8R8A8_UNORM:
	case PIXEL_FORMAT_B8G8R8A8_TYPELESS:
		return PIXEL_FORMAT_B8G8R8A8_UNORM_SRGB;

	case PIXEL_FORMAT_B8G8R8X8_UNORM:
	case PIXEL_FORMAT_B8G8R8X8_TYPELESS:
		return PIXEL_FORMAT_B8G8R8X8_UNORM_SRGB;

	case PIXEL_FORMAT_BC7_TYPELESS:
	case PIXEL_FORMAT_BC7_UNORM:
		return PIXEL_FORMAT_BC7_UNORM_SRGB;

	default:
		return format;
	}

}

Tr2RenderContextEnum::PixelFormat Tr2RenderContextEnum::ConvertDepthStencilFormat( DepthStencilFormat format )
{
	switch( format )
	{
	case DSFMT_D24S8:
	case DSFMT_D24X8:
	case DSFMT_AUTO:
	case DSFMT_READABLE:
		return PIXEL_FORMAT_D24_UNORM_S8_UINT;
	case DSFMT_D24FS8:
		return PIXEL_FORMAT_D24_UNORM_S8_UINT;
	case DSFMT_D16:
	case DSFMT_D16_LOCKABLE:
		return PIXEL_FORMAT_D16_UNORM;
	case DSFMT_D32:
	case DSFMT_D32F:
	case DSFMT_D32F_LOCKABLE:
		return PIXEL_FORMAT_D32_FLOAT;
	default:
		return PIXEL_FORMAT_UNKNOWN;
	}
}

bool Tr2RenderContextEnum::ValidateUsage( BufferUsage usage )
{
	if( usage & USAGE_IMMUTABLE )
	{
		// USAGE_IMMUTABLE is mutually exclusive with everything
		// except hints and READ
		return ( usage & ~( USAGE_HINT_MANAGED | USAGE_CPU_READ ) ) == USAGE_IMMUTABLE;
	}
	if( ( usage & USAGE_LOCK_FREQUENTLY ) && ( usage & USAGE_CPU_READ ) )
	{
		// No reading from USAGE_LOCK_FREQUENTLY resources
		return false;
	}
	return true;
}
