#include "StdAfx.h"

#if TRINITY_PLATFORM == TRINITY_DIRECTX12

#include "Utilities.h"
#include "ALResult.h"
#include "ALLog.h"


namespace
{
// Note: This is not the original version.
// I've changed the SRV and UAV to be texture arrays instead of regular
// textures in order to support 2DARRAY and CUBE textures.
#if 0
	//
	// Generated by Microsoft (R) D3D Shader Disassembler
	//
	//
	// Input signature:
	//
	// Name                 Index   Mask Register SysValue  Format   Used
	// -------------------- ----- ------ -------- -------- ------- ------
	// no Input
	//
	// Output signature:
	//
	// Name                 Index   Mask Register SysValue  Format   Used
	// -------------------- ----- ------ -------- -------- ------- ------
	// no Output
	cs_5_1
		dcl_globalFlags refactoringAllowed
		dcl_constantbuffer CB0[0:0][1], immediateIndexed, space = 0
		dcl_sampler S0[0:0], mode_default, space = 0
		dcl_resource_texture2darray( float, float, float, float ) T0[0:0], space = 0
		dcl_uav_typed_texture2darray( float, float, float, float ) U0[0:0], space = 0
		dcl_input vThreadID.xyz
		dcl_temps 2
		dcl_thread_group 8, 8, 1
		utof r0.xyz, vThreadID.xyzx
		add r1.xy, r0.xyxx, l( 0.500000, 0.500000, 0.000000, 0.000000 )
		mul r0.xy, r1.xyxx, CB0[0][0].xyxx
		utof r0.w, CB0[0][0].z
		sample_l r0.xyzw, r0.xyzx, T0[0].xyzw, S0[0], r0.w
		store_uav_typed U0[0].xyzw, vThreadID.xyzz, r0.xyzw
		ret
		// Approximately 0 instruction slots used
#endif

	const BYTE GenerateMipsArray_main[] =
	{
		 68,  88,  66,  67, 241,  67,
		172, 232, 125,  43, 186,  29,
		188, 227,  51,  90, 246,   4,
		196, 156,   1,   0,   0,   0,
		120,   2,   0,   0,   4,   0,
		  0,   0,  48,   0,   0,   0,
		 64,   0,   0,   0,  80,   0,
		  0,   0, 188,   1,   0,   0,
		 73,  83,  71,  78,   8,   0,
		  0,   0,   0,   0,   0,   0,
		  8,   0,   0,   0,  79,  83,
		 71,  78,   8,   0,   0,   0,
		  0,   0,   0,   0,   8,   0,
		  0,   0,  83,  72,  69,  88,
		100,   1,   0,   0,  81,   0,
		  5,   0,  89,   0,   0,   0,
		106,   8,   0,   1,  89,   0,
		  0,   7,  70, 142,  48,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  1,   0,   0,   0,   0,   0,
		  0,   0,  90,   0,   0,   6,
		 70, 110,  48,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,  88,  64,   0,   7,
		 70, 126,  48,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,  85,  85,
		  0,   0,   0,   0,   0,   0,
		156,  64,   0,   7,  70, 238,
		 49,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,  85,  85,   0,   0,
		  0,   0,   0,   0,  95,   0,
		  0,   2, 114,   0,   2,   0,
		104,   0,   0,   2,   2,   0,
		  0,   0, 155,   0,   0,   4,
		  8,   0,   0,   0,   8,   0,
		  0,   0,   1,   0,   0,   0,
		 86,   0,   0,   4, 114,   0,
		 16,   0,   0,   0,   0,   0,
		 70,   2,   2,   0,   0,   0,
		  0,  10,  50,   0,  16,   0,
		  1,   0,   0,   0,  70,   0,
		 16,   0,   0,   0,   0,   0,
		  2,  64,   0,   0,   0,   0,
		  0,  63,   0,   0,   0,  63,
		  0,   0,   0,   0,   0,   0,
		  0,   0,  56,   0,   0,   9,
		 50,   0,  16,   0,   0,   0,
		  0,   0,  70,   0,  16,   0,
		  1,   0,   0,   0,  70, 128,
		 48,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,  86,   0,   0,   7,
		130,   0,  16,   0,   0,   0,
		  0,   0,  42, 128,  48,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		 72,   0,   0,  13, 242,   0,
		 16,   0,   0,   0,   0,   0,
		 70,   2,  16,   0,   0,   0,
		  0,   0,  70, 126,  32,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,  96,  32,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,  58,   0,  16,   0,
		  0,   0,   0,   0, 164,   0,
		  0,   7, 242, 224,  33,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,  70,  10,   2,   0,
		 70,  14,  16,   0,   0,   0,
		  0,   0,  62,   0,   0,   1,
		 82,  84,  83,  48, 180,   0,
		  0,   0,   1,   0,   0,   0,
		  3,   0,   0,   0,  24,   0,
		  0,   0,   1,   0,   0,   0,
		128,   0,   0,   0,  62,   0,
		  0,   0,   1,   0,   0,   0,
		  0,   0,   0,   0,  60,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,  72,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0, 100,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   3,   0,
		  0,   0,   1,   0,   0,   0,
		 80,   0,   0,   0,   0,   0,
		  0,   0,   1,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0, 255, 255, 255, 255,
		  1,   0,   0,   0, 108,   0,
		  0,   0,   1,   0,   0,   0,
		  1,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		255, 255, 255, 255,  20,   0,
		  0,   0,   3,   0,   0,   0,
		  3,   0,   0,   0,   3,   0,
		  0,   0,   0,   0,   0,   0,
		 16,   0,   0,   0,   4,   0,
		  0,   0,   2,   0,   0,   0,
		  0,   0,   0,   0, 255, 255,
		127, 127,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0
	};
#if 0
	//
	// Generated by Microsoft (R) D3D Shader Disassembler
	//
	//
	// Input signature:
	//
	// Name                 Index   Mask Register SysValue  Format   Used
	// -------------------- ----- ------ -------- -------- ------- ------
	// no Input
	//
	// Output signature:
	//
	// Name                 Index   Mask Register SysValue  Format   Used
	// -------------------- ----- ------ -------- -------- ------- ------
	// no Output
	cs_5_1
		dcl_globalFlags refactoringAllowed
		dcl_constantbuffer CB0[0:0][1], immediateIndexed, space = 0
		dcl_sampler S0[0:0], mode_default, space = 0
		dcl_resource_texture2d( float, float, float, float ) T0[0:0], space = 0
		dcl_uav_typed_texture2d( float, float, float, float ) U0[0:0], space = 0
		dcl_input vThreadID.xy
		dcl_temps 1
		dcl_thread_group 8, 8, 1
		utof r0.xy, vThreadID.xyxx
		add r0.xy, r0.xyxx, l( 0.500000, 0.500000, 0.000000, 0.000000 )
		mul r0.xy, r0.xyxx, CB0[0][0].xyxx
		utof r0.z, CB0[0][0].z
		sample_l r0.xyzw, r0.xyxx, T0[0].xyzw, S0[0], r0.z
		store_uav_typed U0[0].xyzw, vThreadID.xyyy, r0.xyzw
		ret
		// Approximately 0 instruction slots used
#endif

		const BYTE GenerateMips_main[] =
	{
		 68,  88,  66,  67, 189,  63,
		191, 181, 181,  45, 113,   6,
		 56, 182, 109, 157, 174, 172,
		122,  11,   1,   0,   0,   0,
		120,   2,   0,   0,   4,   0,
		  0,   0,  48,   0,   0,   0,
		 64,   0,   0,   0,  80,   0,
		  0,   0, 188,   1,   0,   0,
		 73,  83,  71,  78,   8,   0,
		  0,   0,   0,   0,   0,   0,
		  8,   0,   0,   0,  79,  83,
		 71,  78,   8,   0,   0,   0,
		  0,   0,   0,   0,   8,   0,
		  0,   0,  83,  72,  69,  88,
		100,   1,   0,   0,  81,   0,
		  5,   0,  89,   0,   0,   0,
		106,   8,   0,   1,  89,   0,
		  0,   7,  70, 142,  48,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  1,   0,   0,   0,   0,   0,
		  0,   0,  90,   0,   0,   6,
		 70, 110,  48,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,  88,  24,   0,   7,
		 70, 126,  48,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,  85,  85,
		  0,   0,   0,   0,   0,   0,
		156,  24,   0,   7,  70, 238,
		 49,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,  85,  85,   0,   0,
		  0,   0,   0,   0,  95,   0,
		  0,   2,  50,   0,   2,   0,
		104,   0,   0,   2,   1,   0,
		  0,   0, 155,   0,   0,   4,
		  8,   0,   0,   0,   8,   0,
		  0,   0,   1,   0,   0,   0,
		 86,   0,   0,   4,  50,   0,
		 16,   0,   0,   0,   0,   0,
		 70,   0,   2,   0,   0,   0,
		  0,  10,  50,   0,  16,   0,
		  0,   0,   0,   0,  70,   0,
		 16,   0,   0,   0,   0,   0,
		  2,  64,   0,   0,   0,   0,
		  0,  63,   0,   0,   0,  63,
		  0,   0,   0,   0,   0,   0,
		  0,   0,  56,   0,   0,   9,
		 50,   0,  16,   0,   0,   0,
		  0,   0,  70,   0,  16,   0,
		  0,   0,   0,   0,  70, 128,
		 48,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,  86,   0,   0,   7,
		 66,   0,  16,   0,   0,   0,
		  0,   0,  42, 128,  48,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		 72,   0,   0,  13, 242,   0,
		 16,   0,   0,   0,   0,   0,
		 70,   0,  16,   0,   0,   0,
		  0,   0,  70, 126,  32,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,  96,  32,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,  42,   0,  16,   0,
		  0,   0,   0,   0, 164,   0,
		  0,   7, 242, 224,  33,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,  70,   5,   2,   0,
		 70,  14,  16,   0,   0,   0,
		  0,   0,  62,   0,   0,   1,
		 82,  84,  83,  48, 180,   0,
		  0,   0,   1,   0,   0,   0,
		  3,   0,   0,   0,  24,   0,
		  0,   0,   1,   0,   0,   0,
		128,   0,   0,   0,  62,   0,
		  0,   0,   1,   0,   0,   0,
		  0,   0,   0,   0,  60,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,  72,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0, 100,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   3,   0,
		  0,   0,   1,   0,   0,   0,
		 80,   0,   0,   0,   0,   0,
		  0,   0,   1,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0, 255, 255, 255, 255,
		  1,   0,   0,   0, 108,   0,
		  0,   0,   1,   0,   0,   0,
		  1,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		255, 255, 255, 255,  20,   0,
		  0,   0,   3,   0,   0,   0,
		  3,   0,   0,   0,   3,   0,
		  0,   0,   0,   0,   0,   0,
		 16,   0,   0,   0,   4,   0,
		  0,   0,   2,   0,   0,   0,
		  0,   0,   0,   0, 255, 255,
		127, 127,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,
		  0,   0
	};
}

namespace TrinityALImpl
{
	D3D12_RESOURCE_BARRIER Transition(
		ID3D12Resource* pResource,
		D3D12_RESOURCE_STATES stateBefore,
		D3D12_RESOURCE_STATES stateAfter,
		UINT subresource,
		D3D12_RESOURCE_BARRIER_FLAGS flags )
	{
		D3D12_RESOURCE_BARRIER barrier;
		barrier.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
		barrier.Flags = flags;
		barrier.Transition.pResource = pResource;
		barrier.Transition.StateBefore = stateBefore;
		barrier.Transition.StateAfter = stateAfter;
		barrier.Transition.Subresource = subresource;
		return barrier;
	}

	D3D12_RESOURCE_BARRIER AliasBarrier(
		ID3D12Resource* before,
		ID3D12Resource* after )
	{
		D3D12_RESOURCE_BARRIER desc = {};
		desc.Type = D3D12_RESOURCE_BARRIER_TYPE_ALIASING;
		desc.Aliasing.pResourceBefore = before;
		desc.Aliasing.pResourceAfter = after;
		return desc;
	}

	D3D12_HEAP_PROPERTIES HeapDesc( D3D12_HEAP_TYPE type )
	{
		D3D12_HEAP_PROPERTIES heap = { type, D3D12_CPU_PAGE_PROPERTY_UNKNOWN, D3D12_MEMORY_POOL_UNKNOWN, 0, 0 };
		return heap;
	}

	//------------------------------------------------------------------------------------------------
	// Row-by-row memcpy
	void MemcpySubresource(
		_In_ const D3D12_MEMCPY_DEST* pDest,
		_In_ const D3D12_SUBRESOURCE_DATA* pSrc,
		SIZE_T RowSizeInBytes,
		UINT NumRows,
		UINT NumSlices )
	{
		for( UINT z = 0; z < NumSlices; ++z )
		{
			BYTE* pDestSlice = reinterpret_cast<BYTE*>( pDest->pData ) + pDest->SlicePitch * z;
			const BYTE* pSrcSlice = reinterpret_cast<const BYTE*>( pSrc->pData ) + pSrc->SlicePitch * z;
			for( UINT y = 0; y < NumRows; ++y )
			{
				memcpy( pDestSlice + pDest->RowPitch * y,
					pSrcSlice + pSrc->RowPitch * y,
					RowSizeInBytes );
			}
		}
	}

	//------------------------------------------------------------------------------------------------
	// All arrays must be populated (e.g. by calling GetCopyableFootprints)
	UINT64 UpdateSubresources(
		_In_ ID3D12GraphicsCommandList* pCmdList,
		_In_ ID3D12Resource* pDestinationResource,
		_In_ ID3D12Resource* pIntermediate,
		_In_range_( 0, D3D12_REQ_SUBRESOURCES ) UINT FirstSubresource,
		_In_range_( 0, D3D12_REQ_SUBRESOURCES - FirstSubresource ) UINT NumSubresources,
		UINT64 RequiredSize,
		_In_reads_( NumSubresources ) const D3D12_PLACED_SUBRESOURCE_FOOTPRINT* pLayouts,
		_In_reads_( NumSubresources ) const UINT* pNumRows,
		_In_reads_( NumSubresources ) const UINT64* pRowSizesInBytes,
		_In_reads_( NumSubresources ) const D3D12_SUBRESOURCE_DATA* pSrcData )
	{
		// Minor validation
		D3D12_RESOURCE_DESC IntermediateDesc = pIntermediate->GetDesc();
		D3D12_RESOURCE_DESC DestinationDesc = pDestinationResource->GetDesc();
		if( IntermediateDesc.Dimension != D3D12_RESOURCE_DIMENSION_BUFFER ||
			IntermediateDesc.Width < RequiredSize + pLayouts[0].Offset ||
			RequiredSize >( SIZE_T ) - 1 ||
			( DestinationDesc.Dimension == D3D12_RESOURCE_DIMENSION_BUFFER &&
			( FirstSubresource != 0 || NumSubresources != 1 ) ) )
		{
			return 0;
		}

		BYTE* pData;
		HRESULT hr = pIntermediate->Map( 0, NULL, reinterpret_cast<void**>( &pData ) );
		if( FAILED( hr ) )
		{
			return 0;
		}

		for( UINT i = 0; i < NumSubresources; ++i )
		{
			if( pRowSizesInBytes[i] > ( SIZE_T )-1 ) return 0;
			D3D12_MEMCPY_DEST DestData = { pData + pLayouts[i].Offset, pLayouts[i].Footprint.RowPitch, pLayouts[i].Footprint.RowPitch * pNumRows[i] };
			MemcpySubresource( &DestData, &pSrcData[i], (SIZE_T)pRowSizesInBytes[i], pNumRows[i], pLayouts[i].Footprint.Depth );
		}
		pIntermediate->Unmap( 0, NULL );

		if( DestinationDesc.Dimension == D3D12_RESOURCE_DIMENSION_BUFFER )
		{
			pCmdList->CopyBufferRegion(
				pDestinationResource, 0, pIntermediate, pLayouts[0].Offset, pLayouts[0].Footprint.Width );
		}
		else
		{
			for( UINT i = 0; i < NumSubresources; ++i )
			{
				D3D12_TEXTURE_COPY_LOCATION Dst = { pDestinationResource, D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX, i + FirstSubresource };
				D3D12_TEXTURE_COPY_LOCATION Src = { pIntermediate, D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT, pLayouts[i] };
				pCmdList->CopyTextureRegion( &Dst, 0, 0, 0, &Src, nullptr );
			}
		}
		return RequiredSize;
	}

	//------------------------------------------------------------------------------------------------
	// Heap-allocating UpdateSubresources implementation
	UINT64 UpdateSubresources(
		_In_ ID3D12GraphicsCommandList* pCmdList,
		_In_ ID3D12Resource* pDestinationResource,
		_In_ ID3D12Resource* pIntermediate,
		UINT64 IntermediateOffset,
		_In_range_( 0, D3D12_REQ_SUBRESOURCES ) UINT FirstSubresource,
		_In_range_( 0, D3D12_REQ_SUBRESOURCES - FirstSubresource ) UINT NumSubresources,
		_In_reads_( NumSubresources ) const D3D12_SUBRESOURCE_DATA* pSrcData )
	{
		UINT64 RequiredSize = 0;
		UINT64 MemToAlloc = static_cast<UINT64>( sizeof( D3D12_PLACED_SUBRESOURCE_FOOTPRINT ) + sizeof( UINT ) + sizeof( UINT64 ) ) * NumSubresources;
		if( MemToAlloc > SIZE_MAX )
		{
			return 0;
		}
		void* pMem = HeapAlloc( GetProcessHeap(), 0, static_cast<SIZE_T>( MemToAlloc ) );
		if( pMem == NULL )
		{
			return 0;
		}
		D3D12_PLACED_SUBRESOURCE_FOOTPRINT* pLayouts = reinterpret_cast<D3D12_PLACED_SUBRESOURCE_FOOTPRINT*>( pMem );
		UINT64* pRowSizesInBytes = reinterpret_cast<UINT64*>( pLayouts + NumSubresources );
		UINT* pNumRows = reinterpret_cast<UINT*>( pRowSizesInBytes + NumSubresources );

		D3D12_RESOURCE_DESC Desc = pDestinationResource->GetDesc();
		ID3D12Device* pDevice;
		pDestinationResource->GetDevice( __uuidof( ID3D12Device ), reinterpret_cast<void**>( &pDevice ) );
		pDevice->GetCopyableFootprints( &Desc, FirstSubresource, NumSubresources, IntermediateOffset, pLayouts, pNumRows, pRowSizesInBytes, &RequiredSize );
		pDevice->Release();

		UINT64 Result = UpdateSubresources( pCmdList, pDestinationResource, pIntermediate, FirstSubresource, NumSubresources, RequiredSize, pLayouts, pNumRows, pRowSizesInBytes, pSrcData );
		HeapFree( GetProcessHeap(), 0, pMem );
		return Result;
	}

	UINT64 GetRequiredIntermediateSize(
		_In_ ID3D12Resource* pDestinationResource,
		_In_range_( 0, D3D12_REQ_SUBRESOURCES ) UINT FirstSubresource,
		_In_range_( 0, D3D12_REQ_SUBRESOURCES - FirstSubresource ) UINT NumSubresources )
	{
		auto Desc = pDestinationResource->GetDesc();
		UINT64 RequiredSize = 0;

		ID3D12Device* pDevice = nullptr;
		pDestinationResource->GetDevice( __uuidof( ID3D12Device ), reinterpret_cast<void**>( &pDevice ) );
		pDevice->GetCopyableFootprints( &Desc, FirstSubresource, NumSubresources, 0, nullptr, nullptr, nullptr, &RequiredSize );
		pDevice->Release();

		return RequiredSize;
	}

	D3D12_RESOURCE_DESC BufferDesc( uint64_t size, D3D12_RESOURCE_FLAGS flags )
	{
		D3D12_RESOURCE_DESC resourceDesc = { D3D12_RESOURCE_DIMENSION_BUFFER, 0, size, 1, 1, 1, DXGI_FORMAT_UNKNOWN, 1, 0, D3D12_TEXTURE_LAYOUT_ROW_MAJOR, flags };
		return resourceDesc;
	}


	GenerateMipsResources::GenerateMipsResources( _In_ ID3D12Device* device ) :
		rootSignature( CreateGenMipsRootSignature( device ) )
	{
		generateMipsPSO = CreateGenMipsPipelineState( device, rootSignature, GenerateMips_main, sizeof( GenerateMips_main ) );
		generateMipsArrayPSO = CreateGenMipsPipelineState( device, rootSignature, GenerateMipsArray_main, sizeof( GenerateMipsArray_main ) );
	}

	CComPtr<ID3D12RootSignature> GenerateMipsResources::CreateGenMipsRootSignature( _In_ ID3D12Device* device )
	{
		D3D12_ROOT_SIGNATURE_FLAGS rootSignatureFlags =
			D3D12_ROOT_SIGNATURE_FLAG_DENY_VERTEX_SHADER_ROOT_ACCESS |
			D3D12_ROOT_SIGNATURE_FLAG_DENY_DOMAIN_SHADER_ROOT_ACCESS |
			D3D12_ROOT_SIGNATURE_FLAG_DENY_GEOMETRY_SHADER_ROOT_ACCESS |
			D3D12_ROOT_SIGNATURE_FLAG_DENY_HULL_SHADER_ROOT_ACCESS |
			D3D12_ROOT_SIGNATURE_FLAG_DENY_PIXEL_SHADER_ROOT_ACCESS;

		D3D12_STATIC_SAMPLER_DESC sampler = {
			D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT,
			D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
			D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
			D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
			0,
			0,
			D3D12_COMPARISON_FUNC_ALWAYS,
			D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK,
			0,
			FLT_MAX,
			0, // register
			0,
			D3D12_SHADER_VISIBILITY_ALL
		};

		D3D12_DESCRIPTOR_RANGE sourceDescriptorRange = { D3D12_DESCRIPTOR_RANGE_TYPE_SRV, 1, 0, 0 };
		D3D12_DESCRIPTOR_RANGE targetDescriptorRange = { D3D12_DESCRIPTOR_RANGE_TYPE_UAV, 1, 0, 0 };

		D3D12_ROOT_PARAMETER rootParameters[RootParameterCount] = {};
		rootParameters[Constants].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
		rootParameters[Constants].Constants.Num32BitValues = Num32BitConstants;

		rootParameters[SourceTexture].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
		rootParameters[SourceTexture].DescriptorTable.NumDescriptorRanges = 1;
		rootParameters[SourceTexture].DescriptorTable.pDescriptorRanges = &sourceDescriptorRange;

		rootParameters[TargetTexture].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
		rootParameters[TargetTexture].DescriptorTable.NumDescriptorRanges = 1;
		rootParameters[TargetTexture].DescriptorTable.pDescriptorRanges = &targetDescriptorRange;


		D3D12_ROOT_SIGNATURE_DESC rsigDesc = { _countof( rootParameters ), rootParameters, 1, &sampler, rootSignatureFlags };

		CComPtr<ID3D12RootSignature> rootSignature;
		{
			CComPtr<ID3DBlob> rootSignatureBlob;
			CComPtr<ID3DBlob> errorBlob;
			HRESULT hr;
			CR( hr = D3D12SerializeRootSignature( &rsigDesc, D3D_ROOT_SIGNATURE_VERSION_1_0, &rootSignatureBlob, &errorBlob ) );
			if( FAILED( hr ) )
			{
				if( errorBlob )
				{
					CCP_AL_LOGERR( "Failed to serialize a root signature: %s", static_cast<const char*>( errorBlob->GetBufferPointer() ) );
				}
				else
				{
					CCP_AL_LOGERR( "Failed to serialize a root signature - unknown error" );
				}
			}

			CR( device->CreateRootSignature(
				0,
				rootSignatureBlob->GetBufferPointer(),
				rootSignatureBlob->GetBufferSize(),
				IID_PPV_ARGS( &rootSignature ) ) );
		}

		return rootSignature;
	}

	CComPtr<ID3D12PipelineState> GenerateMipsResources::CreateGenMipsPipelineState(
		_In_ ID3D12Device* device,
		_In_ ID3D12RootSignature* rootSignature,
		_In_reads_( bytecodeSize ) const uint8_t* bytecode,
		_In_ size_t bytecodeSize )
	{
		D3D12_COMPUTE_PIPELINE_STATE_DESC desc = {};
		desc.CS.BytecodeLength = bytecodeSize;
		desc.CS.pShaderBytecode = bytecode;
		desc.pRootSignature = rootSignature;

		CComPtr<ID3D12PipelineState> pso;
		CR( device->CreateComputePipelineState( &desc, IID_PPV_ARGS( &pso ) ) );

		return pso;
	}

	void SetDebugName( ID3D12DeviceChild* resource, const char* name )
	{
		if( resource )
		{
			resource->SetPrivateData( WKPDID_D3DDebugObjectName, UINT( strlen( name ) ), name );
		}
	}

	bool RequiresImmediateBarriers( Tr2GpuUsage::Type gpuUsage )
	{
		return ( gpuUsage & ( Tr2GpuUsage::RENDER_TARGET | Tr2GpuUsage::DEPTH_STENCIL | Tr2GpuUsage::UNORDERED_ACCESS ) ) == 0;
	}
}


#endif