#pragma once


namespace PostProcessEnums
{
	enum AttributeType
	{
		SIGNAL_LOSS_INTENSITY,
		BLOOM_BRIGHTNESS,
		BLOOM_LUMINANCE_THRESHOLD,
		BLOOM_LUMINANCE_SCALE,
		GRIME_INTENSITY,
		GRIME_PATH,
		FILM_GRAIN_INTENSITY,
		FILM_GRAIN_SIZE,
		FILM_GRAIN_DENSITY,
		FILM_GRAIN_CONTRAST,
		FILM_GRAIN_BRIGHTNESS_MODIFIER,
		FILM_GRAIN_COLORED,
		FILM_GRAIN_COLOR_AMOUNT,
		SATURATION,
		FADE_INTENSITY,
		FADE_COLOR,
		LUT_INTENSITY,
		LUT_PATH,
		VIGNETTE_INTENSITY,
		VIGNETTE_OPACITY,
		VIGNETTE_COLOR,
		VIGNETTE_DETAIL1_SIZE,
		VIGNETTE_DETAIL1_SCROLL,
		VIGNETTE_DETAIL2_SIZE,
		VIGNETTE_DETAIL2_SCROLL,
		VIGNETTE_SHAPE_PATH,
		VIGNETTE_DETAIL_PATH,
		VIGNETTE_SINE_FREQUENCY,
		VIGNETTE_MIN_SINE_FREQUENCY,
		VIGNETTE_MAX_SINE_FREQUENCY,
		DEPTH_OF_FIELD_SCALE,
		DEPTH_OF_FIELD_FOCAL_DISTANCE,
		DEPTH_OF_FIELD_FOCAL_LENGTH,
		DEPTH_OF_FIELD_SHAPE,

		WHITE_TEMPERATURE,
		WHITE_TINT,
		COLOR_SATURATION,
		COLOR_CONTRAST,
		COLOR_GAMMA,
		COLOR_GAIN,
		COLOR_OFFSET,


		POST_PROCESS_ATTRIBUTE_TYPE_COUNT 
	};

	extern Be::VarChooser Tr2PostProcessAttributeTypeChooser[];

	enum Priority{
		SCENE_DEFAULT_PRIORITY,
		LOW_PRIORITY,
		MEDIUM_PRIORITY,
		HIGH_PRIORITY,
		UI_PRIORITY,
		PRIORITY_COUNT 
	}; 
	extern Be::VarChooser Tr2PostProcessPriorityChooser[];

};